### ISSUE TITLE
Make decision on 'qx_to_lx' vs 'gen_lx'

### ISSUE THREAD

**Issue by krpaulson** [ihmeuw/lifetableUtils#14]
I like the X_to_X format because it makes it clear what the input parameter(s) is. This isn't super consistent with the gen_X naming format we've used in other cases, but it is consistent with the mx/ax/qx conversions.

Options:
(1) Convert `gen_nLx` to `lx_ax_dx_to_nLx`; `gen_Tx` to `nLx_to_Tx`; and `gen_ex` to `lx_Tx_to_ex`
(2) Convert `qx_to_lx` to `gen_lx`; `lx_to_dx` to `gen_dx`, etc.
(3) Keep as is

**Comment by krpaulson27** [comment]
@chacalle @spencerpease what do you think?

**Comment by chacalle** [comment]
The other important difference is that the mx/ax/qx functions take vectors while all the other lifetable functions take data.tables as input. If they are all `X_to_X` formats you can't tell what inputs are required just from the function name

Maybe another option to make them all consistent is have the mx/ax/qx functions take data.tables as input. Do we ever use them without data.tables?

**Comment by chacalle** [comment]
I'm okay with either option 1 or 2 to make them more consistent with each other

**Comment by krpaulson27** [comment]
So perhaps keep `X_to_X` format for vector inputs (mx/ax/qx functions) and `gen_X` for functions that have data.tables as inputs/outputs?

**Comment by krpaulson27** [comment]
The one I'm getting stuck on is `lx_to_qx` since `gen_qx` isn't particularly descriptive given the number of ways you can calculate qx from different inputs.

**Comment by chacalle** [comment]
Is there a reason we have the mx/ax/qx functions work with vectors?

**Comment by chacalle** [comment]
> The one I'm getting stuck on is `lx_to_qx` since `gen_qx` isn't particularly descriptive given the number of ways you can calculate qx from different inputs.

What about `gen_lx_to_qx`?

**Comment by krpaulson27** [comment]
Or `gen_qx_from_lx`?

**Comment by chacalle** [comment]
Should we change all of them to XX_from_XX and gen_XX_from_XX?
