### ISSUE TITLE
Discuss level of detail in function details vs vignettes

### ISSUE THREAD

**Issue by krpaulson27** [ihmeuw/lifetableUtils#15]
In `gen_lifetable_parameters` @spencerpease commented:
"These details are super helpful, even beyond the scope of this function. I think a vignette would be a better place for this, and it would make formatting and providing examples easier. We could then link to the vignette here."

I agree that these details should be in a vignette, and many of them are in the vignette I already created. But I wanted to open this comment up for discussion for whether they should also be in the function help page. How easy is it to link to a vignette and will that link be reliable and accessible for users?

**Comment by chacalle** [comment]
With the pkgdown site I think its pretty easy to access and view the vignettes. 

But I don't think it hurts to also explain the equations in the function documentation

**Comment by krpaulson27** [comment]
I pared down the documentation within the function help page and added a link to the pkgdown site vignette.
