### ISSUE TITLE
Resolve remaining questions from initial PR

### ISSUE THREAD

**Issue by krpaulson** [ihmeuw/lifetableUtils#3]
- [x] Add sample data to package

- [ ] Expand `lifetableUtils` to include tfr, nrr, leslie matrixes and consider renaming `lifetableUtils` and `demUtils` to reflect this

- [ ] Check mortality code to see if we ever use `assert_na = F`

- [x] Explore and implement `@inheritParams`

- [x] Fix import of `demUtils` into `lifetableUtils`

- [x] Add to documentation for mx, ax, qx conversions

- [x] When do we want to use `age`, or should we always use `age_start` and/or `age_end`?

- [x] Describe README and R package documentation file best practices

**Comment by krpaulson27** [comment]
We do use `assert_na = F` in some parts of the mortality code. When we modify that code to use these packages we should reassess if we can do without this flag.

**Comment by krpaulson27** [comment]
- [ ] Add full life table from Preston

**Comment by krpaulson27** [comment]
Clarify `abridged_to_full` documentation for `id_cols` vs `regression_fits` ids.
